<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BasicCTCs" nsURI="rhea.metamodels.BasicCTCs" nsPrefix="rhea">
  <eClassifiers xsi:type="ecore:EClass" name="Requires" eSuperTypes="#//BasicConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Excludes" eSuperTypes="#//BasicConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicConstraint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftFeature" lowerBound="1"
        eType="ecore:EClass ../BasicFMs/BasicFMs.ecore#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightFeature" lowerBound="1"
        eType="ecore:EClass ../BasicFMs/BasicFMs.ecore#//Feature"/>
  </eClassifiers>
</ecore:EPackage>
