package clafer.Absyn; // Java Package generated by the BNF Converter.

public class CConstraint  extends Constraint {
  public final ListExp listexp_;
  public CConstraint(ListExp p1) { listexp_ = p1; }

  public <R,A> R accept(clafer.Absyn.Constraint.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.CConstraint) {
      clafer.Absyn.CConstraint x = (clafer.Absyn.CConstraint)o;
      return this.listexp_.equals(x.listexp_);
    }
    return false;
  }

  public int hashCode() {
    return this.listexp_.hashCode();
  }


}
