package clafer.Absyn; // Java Package generated by the BNF Converter.

public class MModule  extends Module {
  public final ListDeclaration listdeclaration_;
  public MModule(ListDeclaration p1) { listdeclaration_ = p1; }

  public <R,A> R accept(clafer.Absyn.Module.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.MModule) {
      clafer.Absyn.MModule x = (clafer.Absyn.MModule)o;
      return this.listdeclaration_.equals(x.listdeclaration_);
    }
    return false;
  }

  public int hashCode() {
    return this.listdeclaration_.hashCode();
  }


}
