package clafer.Absyn; // Java Package generated by the BNF Converter.

public class TTransition  extends Transition {
  public final TransArrow transarrow_;
  public final Exp exp_;
  public TTransition(TransArrow p1, Exp p2) { transarrow_ = p1; exp_ = p2; }

  public <R,A> R accept(clafer.Absyn.Transition.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.TTransition) {
      clafer.Absyn.TTransition x = (clafer.Absyn.TTransition)o;
      return this.transarrow_.equals(x.transarrow_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.transarrow_.hashCode())+this.exp_.hashCode();
  }


}
