package clafer.Absyn; // Java Package generated by the BNF Converter.

public class VVarBinding  extends VarBinding {
  public final LocId locid_;
  public final Name name_;
  public VVarBinding(LocId p1, Name p2) { locid_ = p1; name_ = p2; }

  public <R,A> R accept(clafer.Absyn.VarBinding.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof clafer.Absyn.VVarBinding) {
      clafer.Absyn.VVarBinding x = (clafer.Absyn.VVarBinding)o;
      return this.locid_.equals(x.locid_) && this.name_.equals(x.name_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.locid_.hashCode())+this.name_.hashCode();
  }


}
