on:
    push:
        branches:
            - maria  
    workflow_dispatch:
jobs: 
    run_pull:
        name: run pull
        runs-on: ubuntu-latest

        steps:
            -   name: Execiting remote ssh commands using ssh key
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{secrets.SSH_HOST}}
                    username: ${{secrets.SSH_USER}}
                    key: ${{secrets.SSH_PRIVATE_KEY}}
                    port: ${{secrets.SSH_PORT}}
                    script: |
                        cd ${{secrets.WORK_DIR}}                    
                        git switch maria                            
                        git pull                                    
                        cd /home/usuario/rhea/rhea-web/
                        ng build --configuration production --base-href ""
                        sudo cp -r /home/usuario/rhea/rhea-web/dist/ /var/www/
                        sudo systemctl restart server
                        sudo systemctl restart nginx
                        exit   
